### ISSUE TITLE
question/request on additional comfort lighting

### ISSUE THREAD

**Issue by majijn** [trentv4/AdvancedDarkness#5]
is there a way to add more lighting that has the same effect as the comforting lantern on my end?
or does that have to be something you add, if there's nothing in place for end users/modpack makers to add more comfort lighting, would it be feasible to ask for a config to add them?

**Comment by trentv4** [comment]
Added in commit 047df71.

**Comment by trentv4** [comment]
This feature is now included in Advanced Darkness 1.5.
